name: Stock Scanner

on:
  schedule:
    # 한국시간 오후 6시 5분 (UTC 오전 09:05) -> 정각 밀림 현상 방지
    - cron: '5 9 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance mplfinance matplotlib requests beautifulsoup4 lxml
      - name: Run Stock Scanner
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
